[package]
name = "found-it-hello-rs"
license = "Apache-2.0"
description = "First crate to publish"
version = "0.1.19"
edition = "2024"

[lib]
name = "found_it_hello"

[[bin]]
name = "hello"
path = "bin/hello.rs"

[dependencies]
