#
# Cargo Make Configuration
#
[config]
reduce_output = false
skip_core_tasks = true

#
# Environment and Profile Setup
#
[env]
HELLO_BUILD_FLAGS = ""

[env.release]
HELLO_BUILD_FLAGS = "--release"

#
# Tasks
#
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "@@split(HELLO_BUILD_FLAGS, )"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.assets-exist]
script = '''
if [ ! -d ./target/assets ]; then
  echo "./target/assets does not exist"
  exit 1
fi
'''

[tasks.release-exists]
script = '''
if [ ! -d ./target/release ]; then
  echo "./target/release does not exist"
  exit 1
fi
'''

[tasks.assemble-release-assets]
command = "./hack/ci/assemble-release-assets.sh"
dependencies = ["release-exists"]

[tasks.check-gh-installed]
command = "which"
args = ["gh"]

[tasks.upload-release-assets]
command = "./hack/ci/upload-release-assets.sh"
dependencies = ["check-gh-installed", "assets-exist"]
