[config]
reduce_output = false

#
# Environment and Profile Setup
#

[env]
CARGO_BUILD_RUSTFLAGS = ""
EDERA_ASSEMBLE_FORM = { value = "hello", condition = { env_not_set = ["EDERA_ASSEMBLE_FORM"]} }
EDERA_ASSEMBLE_TAG_NAME = { value = "unknown", condition = { env_not_set = ["EDERA_ASSEMBLE_TAG_NAME"]} }
EDERA_ASSEMBLE_PLATFORM = { value = "linux", condition = { env_not_set = ["EDERA_ASSEMBLE_PLATFORM"]} }
EDERA_ASSEMBLE_RELEASE_DIR = { value = "target/release", condition = { env_not_set = ["EDERA_ASSEMBLE_RELEASE_DIR"]} }

[env.release]
CARGO_BUILD_RUSTFLAGS = "--release"

#
# Tasks
#
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.assemble-release-assets]
command = "./hack/ci/assemble-release-assets.sh"

[tasks.check-gh-installed]
command = "which"
args = ["gh"]

[tasks.upload-release-assets]
command = "./hack/ci/upload-release-assets.sh"
dependencies = ["check-gh-installed"]
