name: Binary

on:
  release:
    types:
    - published

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest cargo-make version (from crates.io)
        id: get-version
        run: |
          VERSION=$(curl -s \
            -H "User-Agent: github.com/found-it/hello-rs (contact: jpetersenames@gmail.com)" \
            https://crates.io/api/v1/crates/cargo-make | jq -r '.crate.max_stable_version')
          echo "cargo_make_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo-make binary
        id: cache-cargo-make
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-make
          key: ${{ runner.os }}-cargo-make-${{ steps.get-version.outputs.cargo_make_version }}

      - name: Install cargo-make if missing or outdated
        if: steps.cache-cargo-make.outputs.cache-hit != 'true'
        run: |
          echo "Installing cargo-make ${{ steps.get-version.outputs.cargo_make_version }}"
          cargo install cargo-make --version ${{ steps.get-version.outputs.cargo_make_version }} --force

  upload-artifact:
    if: ${{ github.repository_owner == 'found-it' }}
    name: Upload artifacts
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { os: linux, arch: x86_64, on: ubuntu-latest }
    env:
      TARGET_OS: '${{ matrix.platform.os }}'
      TARGET_ARCH: '${{ matrix.platform.arch }}'
    runs-on: '${{ matrix.platform.on }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-make
        run: cargo install cargo-make
      - name: build
        run: cargo make --profile release build
      - name: 'Assemble hello-rs executable'
        run: |
          tag_name='${{ github.event.release.tag_name }}'
          [ -z $tag_name ] && tag_name='${{ github.event.repository.default_branch }}'
          export EDERA_ASSEMBLE_FORM='hello'
          export EDERA_ASSEMBLE_TAG_NAME="${tag_name}"
          export EDERA_ASSEMBLE_PLATFORM='${{ matrix.platform.os }}-${{ matrix.platform.arch }}'
          export EDERA_ASSEMBLE_RELEASE_DIR='target/release'
          cargo make --profile release assemble-release-assets 
      - name: 'Upload hello to workflow run'
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: hello-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
          path: |
            target/assets/*
      - name: 'Upload all release artifacts'
        run: |
          export HELLO_TAG_NAME='${{ github.event.release.tag_name }}'
          cargo make --profile release upload-release-assets
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
