name: Binary

on:
  release:
    types:
    - published

  pull_request:
    branches:
      - main
    paths:
      - bin/**
      - examples/**
      - src/**
      - Cargo.*
      - rust-toolchain.toml

permissions:
  contents: read

jobs:
  upload-artifact:
    if: ${{ github.repository_owner == 'found-it' }}
    name: Upload artifacts
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { os: linux, arch: x86_64, libc: musl, static: true, on: ubuntu-latest }
        - { os: linux, arch: x86_64, libc: gnu, static: true, on: ubuntu-latest }
        - { os: linux, arch: x86_64, libc: gnu, static: false, on: ubuntu-latest }
    env:
      TARGET_OS: '${{ matrix.platform.os }}'
      TARGET_ARCH: '${{ matrix.platform.arch }}'
      TARGET_LIBC: '${{ matrix.platform.libc }}'
      STATIC_BINARY: '${{ matrix.platform.static }}'
    runs-on: '${{ matrix.platform.on }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: build
        run: cargo make --profile release build
        env:
          STATIC_BINARY: ${{ matrix.platform.static }}

      - name: Fetch latest cargo-make version
        id: name
        run: |
          platform="${TARGET_OS}-${TARGET_ARCH}-${TARGET_LIBC}"
          [ "${STATIC_BINARY}" = "true" && "${TARGET_LIBC}" != "musl" ] && platform="${platform}-static"

          echo "platform=$platform" >> $GITHUB_OUTPUT

      - name: 'Assemble hello-rs executable'
        run: |
          tag_name='${{ github.event.release.tag_name }}'
          [ -z $tag_name ] && tag_name='${{ github.event.repository.default_branch }}'
          export EDERA_ASSEMBLE_FORM='hello'
          export EDERA_ASSEMBLE_TAG_NAME="${tag_name}"
          export EDERA_ASSEMBLE_PLATFORM
          export EDERA_ASSEMBLE_RELEASE_DIR='target/*/release'
          cargo make --profile release assemble-release-assets 
        env:
          STATIC_BINARY: '${{ matrix.platform.static }}'
          EDERA_ASSEMBLE_PLATFORM: '${{ steps.name.outputs.platform }}'

      - name: 'Upload hello to workflow run'
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: hello-${{ steps.name.outputs.platform }}
          path: |
            target/assets/*

      - name: 'Upload all release artifacts'
        if: ${{ github.event_name == 'release' }}
        run: |
          export HELLO_TAG_NAME='${{ github.event.release.tag_name }}'
          cargo make --profile release upload-release-assets
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
