name: Lint and Test Code

on:
  pull_request:
    branches:
      - main
    paths:
      - bin/**
      - examples/**
      - src/**
      - Cargo.*
      - rust-toolchain.toml
      - .github/workflows/ci-code.yaml

permissions:
  contents: read

jobs:
  cache:
    name: setup-cargo-make
    runs-on: ubuntu-latest
    outputs:
      cargo_make_version: ${{ steps.get-version.outputs.cargo_make_version }}
      cache-key: ${{ steps.cache-cargo-make.outputs.cache-primary-key }}
    steps:
      - name: Fetch latest cargo-make version
        id: get-version
        run: |
          VERSION=$(curl -s \
            -H "User-Agent: github.com/found-it/hello-rs (contact: jpetersenames@gmail.com>)" \
            https://crates.io/api/v1/crates/cargo-make | jq -r '.crate.max_stable_version')
          echo "cargo_make_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Cache cargo-make binary
        id: cache-cargo-make
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-make
          key: ${{ runner.os }}-cargo-make-${{ steps.get-version.outputs.cargo_make_version }}

      - name: Install cargo-make if missing or outdated
        if: steps.cache-cargo-make.outputs.cache-hit != 'true'
        run: |
          cargo install cargo-make --version ${{ steps.get-version.outputs.cargo_make_version }} --force

      - name: Verify cargo-make
        run: cargo make --version

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    needs: setup-cargo-make
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: Restore cached cargo-make
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-make
        key: ${{ runner.os }}-cargo-make-${{ needs.setup-cargo-make.outputs.cargo_make_version }}

    - name: 'cargo fmt'
      run: cargo make format-check

  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    needs: setup-cargo-make
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: Restore cached cargo-make
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-make
        key: ${{ runner.os }}-cargo-make-${{ needs.setup-cargo-make.outputs.cargo_make_version }}

    - name: shfmt
      run: |
        GOBIN=/usr/local/bin go install mvdan.cc/sh/v3/cmd/shfmt@latest
        if ! cargo make shfmt; then
          echo ""
          echo "Please run \`cargo make shfmt-write\`"
        fi

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    needs: setup-cargo-make
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: Restore cached cargo-make
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-make
        key: ${{ runner.os }}-cargo-make-${{ needs.setup-cargo-make.outputs.cargo_make_version }}

    - name: shellcheck
      run: cargo make shellcheck

  full-build:
    runs-on: ubuntu-latest
    needs: setup-cargo-make
    strategy:
      fail-fast: false
      matrix:
        arch:
        - x86_64
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
    name: 'Full build linux-${{ matrix.arch }}'
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: Restore cached cargo-make
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-make
        key: ${{ runner.os }}-cargo-make-${{ needs.setup-cargo-make.outputs.cargo_make_version }}

    - name: cargo build
      run: cargo make build

  full-test:
    runs-on: ubuntu-latest
    needs: setup-cargo-make
    strategy:
      fail-fast: false
      matrix:
        arch:
        - x86_64
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
    name: 'Full test linux-${{ matrix.arch }}'
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: Restore cached cargo-make
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-make
        key: ${{ runner.os }}-cargo-make-${{ needs.setup-cargo-make.outputs.cargo_make_version }}

    - name: 'cargo test'
      run: cargo make test

  full-clippy:
    runs-on: ubuntu-latest
    needs: setup-cargo-make
    strategy:
      matrix:
        arch:
        - x86_64
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
    name: 'Full clippy linux-${{ matrix.arch }}'
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: Restore cached cargo-make
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-make
        key: ${{ runner.os }}-cargo-make-${{ needs.setup-cargo-make.outputs.cargo_make_version }}

    - name: 'cargo clippy'
      run: cargo make clippy
