name: Lint and Test Code

on:
  pull_request:
    branches:
      - main
    paths:
      - bin/**
      - examples/**
      - src/**
      - Cargo.*
      - rust-toolchain.toml
      - .github/workflows/ci-code.yaml

permissions:
  contents: read

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: 'Install cargo make'
      run: cargo install cargo-make

    - name: 'cargo fmt'
      run: cargo make format-check

  shfmt:
    name: shfmt
    runs-on: ubuntu-latest
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: shfmt
      run: |
        GOBIN=/usr/local/bin go install mvdan.cc/sh/v3/cmd/shfmt@latest
        if ! cargo make shfmt; then
          echo ""
          echo "Please run \`cargo make shfmt-write\`"
        fi

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: shellcheck
      run: cargo make shellcheck

  full-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - x86_64
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
    name: 'Full build linux-${{ matrix.arch }}'
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: 'Install cargo make'
      run: cargo install cargo-make

    - name: cargo build
      run: cargo make build

  full-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - x86_64
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
    name: 'Full test linux-${{ matrix.arch }}'
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: 'Install cargo make'
      run: cargo install cargo-make

    - name: 'cargo test'
      run: cargo make test

  full-clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
        - x86_64
    env:
      TARGET_ARCH: "${{ matrix.arch }}"
    name: 'Full clippy linux-${{ matrix.arch }}'
    steps:
    - name: harden runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.0
      with:
        submodules: recursive
        persist-credentials: false

    - name: 'Install cargo make'
      run: cargo install cargo-make

    - name: 'cargo clippy'
      run: cargo make clippy
